name: speech-to-text-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - streamlit
      - transformers
      - torch==2.2.0+cpu
      - torchaudio==2.2.0+cpu
      - soundfile
      - numpy
      - ruff
      - pyannote.audio
